---
pygments: true
defaultnav: 
  /: quick_nav.html
  /mcollective: mcollective_menu.html
  /pe/2.7: pe27.html
  /pe/2.6: pe26.html
  /pe/2.5: pe25.html
  /pe/2.0: pe_2.0_nav.markdown
  /puppetdb/0.9: puppetdb0.9.html
  /puppetdb/1: puppetdb1.html
  /puppetdb/1.1: puppetdb1.1.html
  /puppet/2.7/reference: puppet_2_7.html
  /puppet/3/reference: puppet_reference_3.html
  /references: references_general.html
  /hiera/1: hiera1.html
destination: ../output
url: "http://docs.puppetlabs.com"
external_repos:
  puppetdb: git://github.com/puppetlabs/puppetdb.git
  marionette-collective: git://github.com/puppetlabs/marionette-collective.git
external:
  /puppetdb/1.1:
    repo: puppetdb
    branch: 1.1.x
    path: documentation
  /mcollective:
    repo: marionette-collective
    branch: master
    path: website
---
